import type { Lead } from "@/lib/types";

export const demoLeads: Lead[] = [
  {
    id: "demo-1",
    company_name: "Hotel Danubia",
    industry: "hotely",
    city: "Bratislava",
    website: "https://example.com/hotel-danubia",
    public_phone: "+421 2 0000 0000",
    public_email: "recepcia@example.com",
    google_maps_url: "https://maps.google.com/?q=Hotel+Danubia+Bratislava",
    social_url: "https://instagram.com/example",
    data_source: "Demo dataset",
    contact_source: "Verejne uvedený web firmy, demo kontakt",
    description: "Mestský hotel so salónikom a event priestormi.",
    status: "new",
    desired_service: "VR prehliadky",
    notes: "Zaujímavý kandidát na vizuálnu prezentáciu izieb a event priestoru.",
    web_analysis: {
      has_website: true,
      modern_feel: false,
      clear_cta: false,
      mobile_usable: true,
      has_pricing_menu_booking: true,
      quality_photos: false,
      social_presence: true,
      financial_report_available: false,
      has_vr_tour: false,
      vr_potential: true,
      marketing_potential: true,
      chatbot_potential: true,
      social_analysis: "Instagram je uložený, oplatí sa porovnať vizuál izieb a event priestoru s webom.",
      financial_report_note: "Finančné údaje nie sú v demo datasete. V produkcii overiť iba verejný register.",
      vr_tour_note: "VR prehliadka nie je rozpoznaná, fyzické priestory majú vysoký potenciál.",
      marketing_note: "Rezervácia nie je výrazná, priestor je na kampane s jasnejším meraním.",
      chatbot_note: "Chatbot by vedel odpovedať na otázky o izbách, eventoch a dostupnosti.",
      visible_problems: ["Slabé fotky izieb", "Rezervácia nie je výrazná", "Chýba zážitková prezentácia priestoru"],
      summary: "Web existuje, no pri predaji priestoru sa spolieha viac na text než na vizuálny zážitok."
    },
    ai_analysis: {
      main_problem: "Návštevník nevie rýchlo zažiť izby a event priestor pred rezerváciou.",
      sales_angle: "Ukázať priestory cez krátku VR prehliadku a posilniť dôveru pred rezerváciou.",
      recommended_service: "VR prehliadky",
      business_note: "Otvoriť rozhovor cez event priestory a rozhodovanie hostí pred návštevou.",
      call_script:
        "Dobrý deň, volám sa Peter. Pozeral som si váš hotel a všimol som si, že priestory pôsobia zaujímavo, ale online sa nedajú veľmi zažiť. Robíme krátke VR prehliadky, ktoré pomáhajú hosťom lepšie sa rozhodnúť pred rezerváciou. Malo by zmysel, keby som vám poslal ukážku?",
      priority_score: 8
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-2",
    company_name: "FitLab Arena",
    industry: "fitness centrá",
    city: "Trnava",
    website: "https://example.com/fitlab",
    public_phone: null,
    public_email: "info@example.com",
    google_maps_url: "https://maps.google.com/?q=FitLab+Arena+Trnava",
    social_url: "https://facebook.com/example",
    data_source: "Demo dataset",
    contact_source: "Import CSV, demo e-mail",
    description: "Fitness centrum so skupinovými tréningami a osobnými trénermi.",
    status: "callback",
    desired_service: "chatbot",
    notes: "Kontaktovať s návrhom odpovedania na otázky o permanentkách.",
    web_analysis: {
      has_website: true,
      modern_feel: true,
      clear_cta: true,
      mobile_usable: true,
      has_pricing_menu_booking: false,
      quality_photos: true,
      social_presence: true,
      financial_report_available: false,
      has_vr_tour: false,
      vr_potential: false,
      marketing_potential: true,
      chatbot_potential: true,
      social_analysis: "Facebook je uložený, overiť pravidelnosť príspevkov a ponuky tréningov.",
      financial_report_note: "Finančné údaje nie sú v demo datasete. V produkcii overiť iba verejný register.",
      vr_tour_note: "VR nie je hlavná potreba, viac dáva zmysel obsah a konverzia.",
      marketing_note: "Vizuál je silný, príležitosť je v propagácii členstiev a skúšobných vstupov.",
      chatbot_note: "Chatbot môže odľahčiť otázky o permanentkách, otváracích hodinách a tréningoch.",
      visible_problems: ["Cenník je skrytý", "Časté otázky o členstve nie sú pokryté"],
      summary: "Silný vizuál, ale pred návštevou chýbajú rýchle odpovede a prehľad balíkov."
    },
    ai_analysis: {
      main_problem: "Záujemca musí písať alebo volať kvôli základným otázkam o členstve.",
      sales_angle: "Chatbot vie odľahčiť recepciu a priviesť záujemcu k skúšobnému tréningu.",
      recommended_service: "chatbot",
      business_note: "Zdôrazniť menej opakovaných otázok a viac rezervovaných skúšobných vstupov.",
      call_script:
        "Dobrý deň, volám sa Peter. Pozeral som si vaše fitness centrum a vidno, že máte aktívnu komunitu. Záujemca však musí pri základných otázkach o členstve písať alebo volať. Robíme jednoduché chatboty, ktoré odpovedia hneď a nasmerujú ľudí na skúšobný tréning. Môžem vám poslať krátku ukážku?",
      priority_score: 7
    },
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
